dom = circleDomain(radius = 2);
met = gaussMetric(weights=  [1],...
                  widths=   [0.25],...
                  xOffsets= [0],...
                  yOffsets= [0]);
%dom = cosineDomain();
testsurf = RiemannSurface(dom,met);
testsurf.stepType = 'RK4';

figure; hold on;
testsurf.figureJacobiRadiate(-1,...
                              0,...
                              linspace(-pi/4,pi/4, 80), );
met.plot(0.1);
%testsurf.plotConjugates(ones(1,200) * -1,...
%                        ones(1,200) * 0,...
%                        linspace(-pi/4,pi/4, 200));